version: '3.8'

services:
  wms-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../uploads:/app/uploads
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped